### ISSUE TITLE
No output, nor error at all 

### ISSUE THREAD

**Issue by sputnick-dev** [vsetka/deepl-translator-cli#2]
## Bug:

No output, nor error at all : 

```
.yarn/bin/deepl -s EN -t FR "what's the fuck ?"
```

## Environment : 
 - archlinux x86_64
 - node v9.11.1
 - deepl-translator-cli 1.1.0

**Comment by 5t4rdu5t** [comment]
Workaround https://github.com/uinput/deeplator

**Comment by vsetka** [comment]
Repository no longer maintained
