### ISSUE TITLE
Translate error

### ISSUE THREAD

**Issue by juanpebalsa** [vsetka/deepl-translator-cli#3]
I can't do translations after the first installation

```
 # deepl translate -h
deepl-translate(1) does not exist, try --help
```

Node : v8.14.0
deepl: v1.1.2

**Comment by jcvtieck** [comment]
hey,
any solution to this?
I have the same problem.
using deepl on macos.
yarn installed with brew.
yarn: v1.16.0
node: v12.4.0
deepl: v1.1.2

any clues on how to fix this?
thanks,
camilo

**Comment by bodqhrohro** [comment]
This seems to be a bug in the `command` module which this program is based on. When looking for a subcommand, it implies that argv[1] is a subcommand name, though Node.JS reserves first two arguments for the interpreter path and for the main JS module path. I have no idea how could this happen; maybe some older versions of Node.JS reserved only one argument if a script is called via shebang, or the `command` module requires to cut the interpreter out manually. Will investigate it deeper later.

**Comment by vclvm** [comment]
Same here, on linux ubuntu 18.04 with linuxbrew
yarn: v1.16.0
node: v12.5.0
deepl: v1.1.2
Switched to yarn and node installed without linuxbrew, no result.

**Comment by jcvtieck** [comment]
any work around this issue?

**Comment by rg-ch** [comment]
Same here, Manjaro 18.1, 4.19.60-1-MANJARO
yarn 1.17.3
node v11.15.0
deepl 1.1.2 

Thanks for any help

**Comment by fwarmuth** [comment]
+1

**Comment by jcvtieck** [comment]
> Same here, on linux ubuntu 18.04 with linuxbrew
> yarn: v1.16.0
> node: v12.5.0
> deepl: v1.1.2
> Switched to yarn and node installed without linuxbrew, no result.

@looksworking how can we help here?

**Comment by ChrisLuNlm** [comment]
Same here, on linux Red Hat Enterprise Linux Workstation release 7.4 (Maipo)
yarn: v1.17.3
node: v8.16.1
deepl: 1.1.2

The error msg is the same:

deepl-translate(1) does not exist, try --help

Any help or suggestion will be appreciate. Thank you in advance!

**Comment by Sparviero-Sughero** [comment]
+1

**Comment by ChrisLuNlm** [comment]
I believe the DeepL started to charge their API and thus this program does not work anymore!

**Comment by anibalanto** [comment]
+1

**Comment by chrisSCM** [comment]
+1 on Debian 9, deepl installed via yarn

**Comment by c80609a** [comment]
+1 Ubuntu 19

**Comment by return42** [comment]
https://github.com/vsetka/deepl-translator-cli/issues/2#issuecomment-383504283

> Workaround https://github.com/uinput/deeplator

**Comment by nicolasps** [comment]
+1 Ubuntu 19.

Has it at anytime worked? What a disappointment, this is an old bug and seems no body replies on the issues of this project

**Comment by darwinva97** [comment]
+1 Debian 10

**Comment by jnsw** [comment]
+1 macOS

**Comment by LeftH0ok** [comment]
+1

**Comment by LeftH0ok** [comment]
+10086

```

CentOS Linux release 7.9.2009 (Core)

Linux centos 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

yarn version v1.22.15


```

**Comment by vsetka** [comment]
Repository no longer maintained
