### ISSUE TITLE
THIS PROJECT IS BROKEN

### ISSUE THREAD

**Issue by mmontag** [vsetka/deepl-translator-cli#4]
Warning for others. @vsetka, please close the issue if I'm wrong. 
`deepl-translate(1) does not exist, try --help`

**Comment by bserem** [comment]
Duplicate of #3

**Comment by return42** [comment]
https://github.com/vsetka/deepl-translator-cli/issues/2#issuecomment-383504283

> Workaround https://github.com/uinput/deeplator

**Comment by vsetka** [comment]
Repository no longer maintained
