### ISSUE TITLE
Error: Too Many requests

### ISSUE THREAD

**Issue by X-Raym** [vsetka/deepl-translator-cli#5]
Hi, 

I have this error:

`deepl translate -t "EN" "Salut"`

`Unexpected error when parsing deepl split sentence response: {"jsonrpc":"2.0","error":{"code":1042912,"message":"Too many requests."}}`

Seems the project is broken ?

Thx.

**Comment by return42** [comment]
This project is dead.  See https://github.com/vsetka/deepl-translator-cli/issues/2#issuecomment-383504283

> Workaround https://github.com/uinput/deeplator

**Comment by jtrees** [comment]
I presume DeepL changed their API. Funnily enough I get an equivalent error with deeplator:

```
urllib.error.HTTPError: HTTP Error 429: Too many Requests
```

**Comment by return42** [comment]
> Funnily enough I get an equivalent error with deeplator:

Related-to: https://github.com/uinput/deeplator/issues/12

**Comment by nanderer** [comment]
deeplator also has the Too many requests problem

**Comment by vsetka** [comment]
Repository no longer maintained
